server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  application:
    name: payments-ledger
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ledger}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ledger}
    username: ${DATABASE_USER:ledger}
    password: ${DATABASE_PASSWORD:ledger}
    driver-class-name: org.postgresql.Driver

ledger:
  database: ${DATABASE:mongo}
  test-helpers:
    enabled: ${ENABLE_TEST_HELPERS:false}
  sample-data:
    enabled: ${LOAD_SAMPLE_DATA:false}
